### ISSUE TITLE
no portal view in task

### ISSUE THREAD

**Issue by MattOpen** [liffeyd/DNN-DeleteUnauthorisedUsers#1]
Hi ,
i like the idea to delete unauthorised users after a while.
Unfortunately i can`t the view for portal settings in taskplaner.

any thoughts?
thx, matt

**Comment by liffeyd** [comment]
Hi Matt,

I am not sure if I understand your question "Unfortunately i can`t the view for portal settings in taskplaner.". Is it that you cannot find where to change the portal settings? If so what you need is the companion module which you can find here: https://github.com/liffeyd/dwsEditPortalSettings/tree/master/install

**Comment by MattOpen** [comment]
yes, that is what i`am searching for.
Now it works as inspected.
Is there a reason why you split this into two modules?

btw, your subdomain www is`nt working and there is no redirect.
thanks for your time

**Comment by liffeyd** [comment]
Matt,

> Is there a reason why you split this into two modules?

It just seemed like a good idea at the time ;)

What domain are you referring to?

**Comment by MattOpen** [comment]
it was http://www.declanward.com/
but now it`s working :)
